services:
  - type: web
    name: samtech
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 4
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: samtech_db
          property: connectionString
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    buildFilter:
      paths:
      - samtech/**
      - requirements.txt
      - run.py
    disk:
      name: samtech-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: samtech_db
    databaseName: samtech
    plan: free
    postgresMajorVersion: 15
    ipAllowList: []
